### ISSUE TITLE
macOS : specific/fixed utun device name

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tunnel#106] opened 2024-01-27 05:16 UTC
right now, hev creates a random utun name based on a list of current utun devices, e.g. if there are `utun0 utun1 utun2 utun3` before hev runs, then hev creates utun4, no matter what is set for `name:`, you can even set `name: whatever`.

all though we can find it via `netstat -nr | awk '/^198.18.0.1/ {print $4}'` , the ip is one thing we know for sure, because it is configured in yml.

the reason for a fixed utun name is that 1) pf route-to only accept interface name as parameter 2) we don't have to modify pf.conf each time it starts

**Comment by heiher** [comment] 2024-01-27 05:41
If a name is already in use, it cannot be assigned. But we need to let users clearly know that the actual allocated name is different from what is set in the config file. So, isn't it better to report an error when the two are different?

**Comment by heiher** [comment] 2024-01-27 06:16
I confirmed that the current code does not support static specified name. Maintain the routing configuration in the [post-up script](https://github.com/heiher/hev-socks5-tunnel/blob/master/conf/main.yml#L15) so that the actual dynamically assigned name can be obtained in the script's `argv[1]`.

**Comment by heiher** [comment] 2024-01-29 05:40
It seems that macos tun supports both specified names and random assignment. Perhaps random assignment is better? which can effectively avoid failures caused by conflicts.

**Comment by heiher** [comment] 2024-01-29 05:53
Looks good to me. I think we can support both:

#### specified name

```yaml
tunnel:
    name: utunN # (N is a number)
```

if the specified utun is in use, just emit an error and exit.

#### random assign name

```yaml
tunnel:
    name: utun
```

**Comment by heiher** [comment] 2024-01-29 13:43
Fixed by: https://github.com/heiher/hev-socks5-tunnel/commit/9790dea4547bb9d6ca68d86058b2ed9a2c7353c7

**Closed by heiher** 2024-01-29 13:43 UTC
